drop table if exists customers cascade;

drop table if exists order_product cascade;

drop table if exists order_service cascade;

drop table if exists order_staff cascade;

drop table if exists orders cascade;

drop table if exists products cascade;

drop table if exists services cascade;

drop table if exists staves cascade;

drop table if exists wallets cascade;

create table
  customers (
    id integer generated by default as identity,
    name varchar(255),
    address varchar(255),
    phone varchar(255),
    wallet_id integer,
    primary key (id)
  );

create table
  order_product (
    order_id integer not null,
    product_id integer not null,
    primary key (order_id, product_id)
  );

create table
  order_service (
    service_id integer not null,
    order_id integer not null,
    primary key (service_id, order_id)
  );

create table
  order_staff (
    staff_id integer not null,
    order_id integer not null,
    primary key (staff_id, order_id)
  );

create table
  orders (
    id integer generated by default as identity,
    note varchar(255),
    status varchar(255) not null,
    time_estimate date not null,
    time_order date not null,
    total_price float (53) not null,
    customer_id integer not null,
    primary key (id)
  );

create table
  products (
    id integer generated by default as identity,
    name varchar(255),
    color varchar(255) not null,
    status varchar(255) not null,
    primary key (id)
  );

create table
  services (
    id integer generated by default as identity,
    name varchar(255),
    fee float (53) not null,
    primary key (id)
  );

create table
  staves (
    id integer generated by default as identity,
    name varchar(255),
    phone varchar(255),
    wallet_id integer,
    primary key (id)
  );

create table
  wallets (
    id integer generated by default as identity,
    account_num varchar(255) not null,
    balance float (53) not null,
    primary key (id)
  );

create index order_time_order on orders (time_order asc);

alter table if exists wallets add constraint UK_ruy3pt1e3xnsal1j3sr0t9y6f unique (account_num);

alter table if exists customers add constraint FKgxyl9e7yv2oggimotl3ck6shb foreign key (wallet_id) references wallets;

alter table if exists order_product add constraint FKo6helt0ucmegaeachjpx40xhe foreign key (product_id) references products;

alter table if exists order_product add constraint FKl5mnj9n0di7k1v90yxnthkc73 foreign key (order_id) references orders;

alter table if exists order_service add constraint FKq63mqdm9abe2kw0hsa1qh4pdw foreign key (order_id) references orders;

alter table if exists order_service add constraint FKgc67yeomlx546t08eep9k3sc8 foreign key (service_id) references services;

alter table if exists order_staff add constraint FK2nlr8vkdq594kacjbglahs9kw foreign key (order_id) references orders;

alter table if exists order_staff add constraint FKh416ar0aex5oiyxcwphqy4lll foreign key (staff_id) references staves;

alter table if exists orders add constraint FKpxtb8awmi0dk6smoh2vp1litg foreign key (customer_id) references customers;

alter table if exists staves add constraint FKbcokbc5rnim3jx4ml49pfdfw4 foreign key (wallet_id) references wallets;
